name: reviewdog
on: [push]
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dbelyaev/action-checkstyle@v0.5.1
        with:
          github_token: ${{ secrets.github_token }}
          level: warning