name: reviewdog
on: [push]
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dbelyaev/action-checkstyle@v0.5.1
        with:
          github_token: ${{ secrets.github_token }}
          level: error

      - name: Upload  Results for
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Report
          path: target/site/serenity/lint/

