name: Regression Tests Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests from'
        required: false
        default: 'main'
      browser:
        description: 'browser to run tests'
        required: true
        type: choice
        options:
          - chrome
          - firefox
          - edge

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Setup Chrome
        if: contains(github.event.inputs.browser,'chrome')
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: latest

      - name: Run Regression Tests
        run:  mvn clean verify serenity:aggregate -Dwebdriver.driver=${{github.event.inputs.browser}}

      - name: Upload Serenity Results for ${{github.event.inputs.browser}}
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Serenity Report for ${{github.event.inputs.browser}}
          path: target/site/serenity

      name: Lint

      on:
        # Trigger the workflow on push or pull request,
        # but only for the main branch
        push:
          branches:
            - main
        pull_request:
          branches:
            - main

      jobs:
        run-linters:
          name: Run linters
          runs-on: ubuntu-latest

          steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                node-version: 12

            # ESLint and Prettier must be in `package.json`
            - name: Install Node.js dependencies
              run: npm ci

            - name: Run linters
              uses: wearerequired/lint-action@v2
              with:
                eslint: true
                prettier: true