name: Java CI with Maven on Safari Mac OS

on:
  push:
    branches: [ci-cd/workflows]
  pull_request:
    branches: [ci-cd/workflows]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean verify serenity:aggregate -Dwebdriver.driver=safari
        
